AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 100
Style/FrozenStringLiteralComment:
  Enabled: false
