require: rubocop-rspec
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
   - 'Guardfile'
   - 'db/migrate/*'
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 100
RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/*'
RSpec/ExampleLength:
  Exclude:
    - 'spec/features/**/*'
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInLiteral: # hash or array with comma on last element
  Enabled: false
