mysql: &mysql
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  host: localhost

default: &default
 <<: *mysql

development:
  <<: *default
  database: health_development

test:
  <<: *default
  database: health_test

production:
  <<: *mysql
  url: <%= ENV['CLEARDB_DATABASE_URL'] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  database: health_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
